In [2]:
a = [0, 1, 2, 3]
print (a)
print(type(a))

[0, 1, 2, 3]
<class 'list'>


NumPy
NumPy (Numerical Python) is an open source Python library that aids in mathematical and scientific programming.
NumPy is the fundamental package for scientific computing with Python. It contains:	ID'
*	a powerful N-dimensional array object
*	extension package to Python for multi-dimensional arrays0>
*	designed for scientific computation -- linear algebra and random numbe
*	capabilities
*	NumPy is incredible library to perform mathematical and statistical op erations due to it's fast and memory efficient.
 
*	This allows NumPy to iety of databases


In [3]:
 ##Import NumPy
import numpy as np


In [5]:
a=[1,2,3,4,5]
np_a = np.array(a)
print(np_a)


[1 2 3 4 5]


In [6]:
print(type(np_a))

<class 'numpy.ndarray'>


                                        Creating NumPv Arrays From a List

In [7]:
#  1-Da = np.array([ ,
a = np.array([0, 1, 2, 3])
print (a)

[0 1 2 3]


In [9]:
1 #print dimensions
a.ndim


1

In [10]:
#shape
a.shape

(4,)

In [11]:
#2-D
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b)

[[0 1 2]
 [3 4 5]]


In [12]:
b.ndim

2

In [13]:
b.shape

(2, 3)

In [14]:
 # We can convert a matrix which is also a list to array
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

b = np.array(my_matrix)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
b.shape

(3, 3)

In [ ]:
                                            arange
•	arange is an array-valued version of the built-in Python range function
•	Syntax: np.arange(start,end,step)


In [18]:
np.arange(10, 100, 10) #start, end (excLusive), step 

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.zeros((3,)) 

array([0., 0., 0.])

In [21]:
np.zeros((3,3)) # zero matrix or nuLL matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.random.randint(1,41,5)


array([35, 33,  1, 35, 40])

In [24]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel()


array([1, 2, 3, 4, 5, 6])

In [25]:
#Reshape array
arr = np.arange(20)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)


In [26]:
# Notice the two sets of brackets
a1=arr.reshape(5,4)
a1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [27]:
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [28]:
 b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [29]:
        #Transpose array
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [31]:
c = a.T
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [32]:
#Copy array
a = np.array([1,2,3])
b = a #shallow copy
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [33]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [34]:
#Sort
np.sort([4,6,8,2,1])

array([1, 2, 4, 6, 8])

In [36]:
#Sorting aLong an axis: axis=1 --> row and axis=0 -->coLumn
a = np.array([[5, 4, 6], [2, 8, 2]])
b = np.sort(a)
b

array([[4, 5, 6],
       [2, 2, 8]])

In [39]:
#Add/Remove operations on a numpy array
a = np.array([4,7,8])
a = np.append(a, [2,4,5])
print('Numpy array after addition:',a)

Numpy array after addition: [4 7 8 2 4 5]


In [41]:
a = np.delete(a, 2)
print('Numpy array after deletion of one element:',a)

Numpy array after deletion of one element: [4 7 2 4 5]


In [42]:
#Indexing

a = np.arange(3,10)
print(a)
print(a[5])

[3 4 5 6 7 8 9]
8


In [43]:
a[5]=50
print(a)

[ 3  4  5  6  7 50  9]


In [44]:
a = np.diag([1, 2, 3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [45]:
print(a[2,1])

0


In [47]:
a[2,1]=5 #assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [48]:
#Indexing with an array of integers
a = np.arange(0, 101, 10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [49]:
a [2]

20

In [50]:
#Indexing can be done with an array of integers, where the same index is rep
a[[2, 3, 2, 4, 9 ]]

array([20, 30, 20, 40, 90])

In [51]:
a[2]=100

In [52]:
# New values can be assigned
a[[1, 10]] = 1000
a


array([   0, 1000,  100,   30,   40,   50,   60,   70,   80,   90, 1000])

In [53]:
#Mask indexing or Fancy indexing
a = np.array([15, 6, 21, 16, 4])
a

array([15,  6, 21, 16,  4])

In [54]:
a%2==0

array([False,  True, False,  True,  True])

In [63]:
#Slicing
a = np.arange(4,18)
a

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [64]:
a[1:8:2] #[startindex: endindex(exclusive):step]

array([ 5,  7,  9, 11])

In [70]:
#Arthimetic Operations
a = np.array([1, 2, 3, 4]) #create an array
print(a)
a



[1 2 3 4]


array([1, 2, 3, 4])

In [71]:
print(a+1)

[2 3 4 5]


In [72]:
a**2

array([ 1,  4,  9, 16])

In [73]:
b = np.ones((4,)) + 1
b


array([2., 2., 2., 2.])

In [74]:
a+b

array([3., 4., 5., 6.])

In [76]:
a-b

array([-1.,  0.,  1.,  2.])

In [78]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[4,4],[4,4],[4,4]])


# adding a and b
print(a+b)

[[ 5  6]
 [ 7  8]
 [ 9 10]]


In [79]:
## multiply a and b - elementwise multiplication
print(a*b)

[[ 4  8]
 [12 16]
 [20 24]]


In [81]:
# matrix multiplication
a = np.array([[1,2,1], [3,4,3],[5,6,5]])
b = np.array([[4,4,1], [4,4,2],[4,4,3]])
np.matmul(a,b)

array([[16, 16,  8],
       [40, 40, 20],
       [64, 64, 32]])

In [82]:
#Comparision operations
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a == b


array([False,  True, False,  True])

In [83]:
a > b

array([False, False,  True, False])

In [85]:
#array-wise comparisions

a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [86]:
np.array_equal(a, b)

False

In [87]:
np.array_equal(a, c)

True

In [88]:
#Mathematical operations
a = np.arange(0,6)
a


array([0, 1, 2, 3, 4, 5])

In [89]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [90]:
np.log(a)

C:\Users\HI\AppData\Local\Temp\ipykernel_17152\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791])

In [91]:
np.exp(a) #evalyatese'x for each element ina given tnput

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])